version: '3.9'

services:
  spring-school-analysis:

    build:
      context: .
      dockerfile: Dockerfile
    image: spring2021_lab:latest
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./spring_school_ss2021/:/home/jovyan/notebooks
      - ./Tweets/:/home/jovyan/tweets
    ports:
      - "8885:8888"
    command: bash -c "start.sh jupyter lab --LabApp.token=''"